// --- PCB helpers ---------------------------------------------------------

/**
 * Remove all copper track segments generated by the TS circuit-synth engine
 * before handing the PCB to Freerouting.  Those tracks were placed at
 * pre-placement component positions and become dangling ends after
 * /place/auto moves the footprints.
 *
 * Freerouting routes from scratch on clean pads; keep the original PCB
 * as a fallback so callers can restore it when Freerouting is unavailable.
 */
export function stripTrackSegments(pcbContent: string): string {
  // Handle both single-line `(segment ...)` and multi-line KiCad 7/8 format
  // where pcbnew reformats tracks as `(segment\n  (start ...)\n  ...\n)`.
  // Track paren depth so we skip exactly the lines belonging to each block.
  const lines = pcbContent.split('\n');
  const result: string[] = [];
  let depth = 0;
  let inSegment = false;

  for (const line of lines) {
    if (!inSegment && line.trimStart().startsWith('(segment')) {
      inSegment = true;
      depth = 0;
      for (const ch of line) {
        if (ch === '(') depth++;
        else if (ch === ')') depth--;
      }
      if (depth <= 0) inSegment = false; // single-line — closed on same line
      continue; // always skip the opening line
    }
    if (inSegment) {
      for (const ch of line) {
        if (ch === '(') depth++;
        else if (ch === ')') depth--;
      }
      if (depth <= 0) inSegment = false;
      continue; // skip body / closing line
    }
    result.push(line);
  }

  return result.join('\n');
}

/**
 * Add a GND copper fill (ground plane) on B.Cu covering the full board area.
 * Guarantees GND connectivity even when Freerouting fails to route the GND net
 * (e.g. when it's blocked by signal traces on F.Cu with no available path).
 * Industry-standard practice: route signals on F.Cu, GND plane on B.Cu.
 */
export function addGroundPlane(pcbContent: string, boardW: number, boardH: number): string {
  const netMatch = pcbContent.match(/\(net (\d+) "GND"\)/);
  if (!netMatch) return pcbContent;
  const netId = netMatch[1];

  const zone = [
    `  (zone (net ${netId}) (net_name "GND") (layer "B.Cu") (hatch edge 0.508)`,
    `    (connect_pads yes (clearance 0.5))`,
    `    (min_thickness 0.25)`,
    `    (fill yes (thermal_gap 0.5) (thermal_bridge_width 0.5))`,
    `    (polygon`,
    `      (pts`,
    `        (xy 0 0) (xy ${boardW} 0) (xy ${boardW} ${boardH}) (xy 0 ${boardH})`,
    `      )`,
    `    )`,
    `  )`,
  ].join('\n');

  const trimmed = pcbContent.trimEnd();
  return trimmed.endsWith(')') ? trimmed.slice(0, -1) + '\n' + zone + '\n)' : pcbContent + '\n' + zone;
}
